# CirrusCI - test builds on FreeBSD instances
# See: https://cirrus-ci.org; https://cirrus-ci.org/guide/FreeBSD/

freebsd_ci_task:

  freebsd_instance:
    # See the list of available FreeBSD image families here: https://cirrus-ci.org/guide/FreeBSD/
    matrix:
      - image_family: freebsd-14-1 # FreeBSD 14.1-RELEASE

  env:
    matrix:
      QJS_CI_CONFIGTYPE: Debug
      QJS_CI_CONFIGTYPE: Release
      QJS_CI_CONFIGTYPE: examples
      QJS_CI_CONFIGTYPE: shared

  install_deps_script:
    - pkg update -f
    - pkg clean -a -y
    - pkg install -y git cmake ninja pkgconf

  init_git_submodules_script: git submodule update --init --recursive

  set_build_env_script: |
    if [ "$QJS_CI_CONFIGTYPE" = "Debug" ]; then
      echo "BUILD_TYPE=Debug" >> $CIRRUS_ENV;
    elif [ "$QJS_CI_CONFIGTYPE" = "Release" ]; then
      echo "BUILD_TYPE=Release" >> $CIRRUS_ENV;
    elif [ "$QJS_CI_CONFIGTYPE" = "examples" ]; then
      echo "QJS_BUILD_EXAMPLES=ON" >> $CIRRUS_ENV;
    elif [ "$QJS_CI_CONFIGTYPE" = "shared" ]; then
      echo "BUILD_SHARED_LIBS=ON" >> $CIRRUS_ENV;
    elif [ "$QJS_CI_CONFIGTYPE" = "asan+ubsan" ]; then
      echo "BUILD_TYPE=RelWithDebInfo" >> $CIRRUS_ENV;
      echo "QJS_ENABLE_ASAN=ON" >> $CIRRUS_ENV;
      echo "QJS_ENABLE_UBSAN=ON" >> $CIRRUS_ENV;
    fi

  stats_task:
    only_if: $QJS_CI_CONFIGTYPE != 'examples'
    script: make stats

  cxxtest_task:
    script: make cxxtest

  test_task:
    only_if: $QJS_CI_CONFIGTYPE != 'examples'
    script: make test

  test_examples_task:
    only_if: $QJS_CI_CONFIGTYPE == 'examples'
    script: |
      cp build/fib.so examples/
      cp build/point.so examples/
      ./build/qjs examples/test_fib.js
      ./build/qjs examples/test_point.js
      ./build/qjs tests/test_bjson.js
      ./build/function_source

  test_262_task:
    only_if: $QJS_CI_CONFIGTYPE == 'Release'
    script: |
      git submodule update --init --checkout --depth 1
      time make test262

  test_standalone_task:
    script: |
      ./build/qjs -c examples/hello.js -o hello
      ./hello

  test_interrupt_task:
    script: ./build/interrupt-test
